### ISSUE TITLE
Vignette Effect?

### ISSUE THREAD

**Issue by pushqrdx** [tannerc/spf#2]
It would be super awesome if you can add a Vignette effect similar to the one f.lux provides on windows, It adds a vignette like overlay to the screen with the edges a little bit darker than the center, Super useful for reducing eye strain.

**Comment by tannerc** [comment]
Thanks for the idea, but Spf was intentionally built for presenting, not for easing eye strain. It is a free, open source project however, so if someone wants to take this on as an additional feature they're more than welcome to!
