### ISSUE TITLE
Multipule screens

### ISSUE THREAD

**Issue by effendrew** [tannerc/spf#3]
trying to use with Mojave and 3 screens.  SPF only works on 2 of the screens, but I can change the menu bar setting on all three.

tia

**Comment by tannerc** [comment]
Will look into this once I have access to three monitors!

**Comment by tannerc** [comment]
Was able to repo successfully. Something about scaled screen resolutions. Will look into it and try to get an update out before too long.

**Comment by tannerc** [comment]
Tested latest branch on three screens with no problems. Please let me know if you encounter this again in future releases.
